var quotes = ['“Be yourself; everyone else is already taken.”― Oscar Wilde', '“You only live once, but if you do it right, once is enough.”― Mae West', '“Be the change that you wish to see in the world.”― Mahatma Gandhi', '“In three words I can sum up everything I\'ve learned about life: it goes on.”― Robert Frost', '“If you tell the truth, you don\'t have to remember anything.”― Mark Twain', '“A friend is someone who knows all about you and still loves you.”― Elbert Hubbard', '“Always forgive your enemies; nothing annoys them so much.”― Oscar Wilde', '“To live is the rarest thing in the world. Most people exist, that is all.”― Oscar Wilde', '“Live as if you were to die tomorrow. Learn as if you were to live forever.”― Mahatma Gandhi', '“I am so clever that sometimes I don\'t understand a single word of what I am saying.”― Oscar Wilde', '“Insanity is doing the same thing, over and over again, but expecting different results.”― Narcotics Anonymous','“Curiosity about life in all of its aspects, I think, is still the secret of great creative people.” – Leo Burnett','“If you want to live a happy life, tie it to a goal, not to people or things.”– Albert Einstein','“Money and success don’t change people; they merely amplify what is already there.” — Will Smith','“Your time is limited, so don’t waste it living someone else’s life. Don’t be trapped by dogma – which is living with the results of other people’s thinking.” – Steve Jobs','“Never let the fear of striking out keep you from playing the game.”– Babe Ruth','“The purpose of our lives is to be happy.” — Dalai Lama','“Life is what happens when you’re busy making other plans.” — John Lennon','“Many of life’s failures are people who did not realize how close they were to success when they gave up.”– Thomas A. Edison','“No one can defeat a powerful mind.” ~ Chanakya','“Learn from the mistakes of others….. you can’t live long enough to make them all yourselves” ~ Chanakya','“Even if a snake is not poisonous, it should pretend to be venomous.” ~ Chanakya','“A person should not be too honest. Straight trees are cut first and honest people are screwed first” ~ Chanakya','“A man is great by deeds, not by birth.” ~ Chanakya','“Humbleness is at the root of self control.” ~ Chanakya','“Education is the best friend. An educated person is respected everywhere. Education beats the beauty and the youth.” ~ Chanakya','“Till the full stop doesn\'t come the sentence is not complete. ~ M.S. Dhoni”']

// function newQuote() {
//     var rand = Math.floor(Math.random() * (quotes.length - 1));
//     document.getElementById("quotes").innerHTML = quotes[rand];
// }

function newQuote() {
        setInterval(function() {
            var rand = Math.floor(Math.random() * (quotes.length - 1));
            document.getElementById("quotes").innerHTML = quotes[rand];
        }, 5000);
    }
